del  .\Order.Api\bin\*.*   /s /q
del  .\Order.Api\obj\*.*   /s /q
del  .\Order.Api\wwwroot\ui\*.*   /s /q
del  .\Order.Api\WMBlog.db   /s /q
del  .\Order.Common\bin\*.*   /s /q
del  .\Order.Common\obj\*.*   /s /q
del  .\Order.EventBus\bin\*.*   /s /q
del  .\Order.EventBus\obj\*.*   /s /q
del  .\Order.Extensions\bin\*.*   /s /q
del  .\Order.FrameWork\bin\*.*   /s /q
del  .\Order.Gateway\bin\*.*   /s /q
del  .\Order.IServices\bin\*.*   /s /q
del  .\Order.Model\bin\*.*   /s /q
del  .\Order.Repository\bin\*.*   /s /q
del  .\Order.Serilog.Es\bin\*.*   /s /q
del  .\Order.Services\bin\*.*   /s /q
del  .\Order.Tasks\bin\*.*   /s /q
del  .\Order.Tests\bin\*.*   /s /q
del  .\Ocelot.Provider.Nacos\bin\*.*   /s /q

del  .\Order.Extensions\obj\*.*   /s /q
del  .\Order.FrameWork\obj\*.*   /s /q
del  .\Order.Gateway\obj\*.*   /s /q
del  .\Order.IServices\obj\*.*   /s /q
del  .\Order.Model\obj\*.*   /s /q
del  .\Order.Repository\obj\*.*   /s /q
del  .\Order.Serilog.Es\obj\*.*   /s /q
del  .\Order.Services\obj\*.*   /s /q
del  .\Order.Tasks\obj\*.*   /s /q
del  .\Order.Tests\obj\*.*   /s /q
del  .\Ocelot.Provider.Nacos\obj\*.*   /s /q