del  .\Inventory.Api\bin\*.*   /s /q
del  .\Inventory.Api\obj\*.*   /s /q
del  .\Inventory.Api\wwwroot\ui\*.*   /s /q
del  .\Inventory.Api\WMBlog.db   /s /q
del  .\Inventory.Common\bin\*.*   /s /q
del  .\Inventory.Common\obj\*.*   /s /q
del  .\Inventory.EventBus\bin\*.*   /s /q
del  .\Inventory.EventBus\obj\*.*   /s /q
del  .\Inventory.Extensions\bin\*.*   /s /q
del  .\Inventory.FrameWork\bin\*.*   /s /q
del  .\Inventory.Gateway\bin\*.*   /s /q
del  .\Inventory.IServices\bin\*.*   /s /q
del  .\Inventory.Model\bin\*.*   /s /q
del  .\Inventory.Repository\bin\*.*   /s /q
del  .\Inventory.Serilog.Es\bin\*.*   /s /q
del  .\Inventory.Services\bin\*.*   /s /q
del  .\Inventory.Tasks\bin\*.*   /s /q
del  .\Inventory.Tests\bin\*.*   /s /q
del  .\Ocelot.Provider.Nacos\bin\*.*   /s /q

del  .\Inventory.Extensions\obj\*.*   /s /q
del  .\Inventory.FrameWork\obj\*.*   /s /q
del  .\Inventory.Gateway\obj\*.*   /s /q
del  .\Inventory.IServices\obj\*.*   /s /q
del  .\Inventory.Model\obj\*.*   /s /q
del  .\Inventory.Repository\obj\*.*   /s /q
del  .\Inventory.Serilog.Es\obj\*.*   /s /q
del  .\Inventory.Services\obj\*.*   /s /q
del  .\Inventory.Tasks\obj\*.*   /s /q
del  .\Inventory.Tests\obj\*.*   /s /q
del  .\Ocelot.Provider.Nacos\obj\*.*   /s /q